# robot_controller.py
import mujoco
import numpy as np
import time

class RobotController:
    """
    A professional-grade controller for the Franka Emika Panda arm in MuJoCo.

    This controller uses a torque-based PID controller at the joint level to track
    trajectories generated by a differential inverse kinematics (IK) solver.
    This allows for smooth and precise control of the end-effector in Cartesian space.
    """
    def __init__(self, model, data, n_disks=3):
        """Initializes the RobotController."""
        self.model = model
        self.data = data
        self.n_disks = n_disks

        # --- Get MuJoCo IDs ---
        # Actuators
        self.actuator_names = [f'actuator{i+1}' for i in range(7)]
        self.arm_actuator_ids = np.array([mujoco.mj_name2id(self.model, mujoco.mjtObj.mjOBJ_ACTUATOR, name) for name in self.actuator_names])
        self.gripper_actuator_id = mujoco.mj_name2id(self.model, mujoco.mjtObj.mjOBJ_ACTUATOR, "actuator8")

        # Joints
        self.joint_names = ['joint1', 'joint2', 'joint3', 'joint4', 'joint5', 'joint6', 'joint7']
        self.arm_joint_ids = np.array([mujoco.mj_name2id(self.model, mujoco.mjtObj.mjOBJ_JOINT, name) for name in self.joint_names])

        # --- Internal State Tracking ---
        self.peg_state = {
            'A': [f'disk_body{i}' for i in range(self.n_disks, 0, -1)],
            'B': [],
            'C': []
        }
        
    def move(self, j1=None, j2=None, j3=None, j4=None, j5=None, j6=None, j7=None, gripper=None):
        """Set joint positions directly.
        
        Args:
            j1-j7: Target joint angles in radians (None = don't move that joint)
            gripper: Target gripper position 0-255 (None = don't move gripper)
        """
        # Simple direct control - no deadband, no smooth movement
        if j1 is not None:
            self.data.ctrl[self.actuator_indices['joint1']] = j1
        if j2 is not None:
            self.data.ctrl[self.actuator_indices['joint2']] = j2
        if j3 is not None:
            self.data.ctrl[self.actuator_indices['joint3']] = j3
        if j4 is not None:
            self.data.ctrl[self.actuator_indices['joint4']] = j4
        if j5 is not None:
            self.data.ctrl[self.actuator_indices['joint5']] = j5
        if j6 is not None:
            self.data.ctrl[self.actuator_indices['joint6']] = j6
        if j7 is not None:
            self.data.ctrl[self.actuator_indices['joint7']] = j7
        if gripper is not None:
            self.data.ctrl[self.gripper_actuator_id] = gripper

    def load_execute_hanoi_moves(self, solution, viewer=None): 
        print(f"▶️ Loading and executing Hanoi moves: {solution}")
        for i, move in enumerate(solution):
            source_peg, target_peg = move
            #if self.data.ctrl[self.gripper_actuator_id] == 0:
            #    self.data.ctrl[self.gripper_actuator_id] = 255
            #else:
            #    self.data.ctrl[self.gripper_actuator_id] = 0

        print("\n🎉 Tower of Hanoi puzzle solved!")

    def execute_hanoi_move(self, source_peg, target_peg, viewer=None):
        """
        Executes a full pick-and-place sequence for a single abstract Hanoi move.
        """
        # 1. Identify which disk to move and determine heights from internal state
        if not self.peg_state[source_peg]:
            print(f"⚠️ Warning: Attempted to pick from empty peg {source_peg}. Skipping move.")
            return
            
        disk_to_move_body_name = self.peg_state[source_peg][-1]
        disk_id_str = disk_to_move_body_name.replace('disk_body', '')

        source_level = len(self.peg_state[source_peg])
        target_level = len(self.peg_state[target_peg]) + 1

        # Define the sequence of sites to target
        approach_site_src = f"post{source_peg}_approach"
        grasp_site = f"disk{disk_id_str}_grasp_top"
        place_site = f"post{target_peg}_level{target_level}"
        approach_site_tgt = f"post{target_peg}_approach"

        print(f"\n🤖 === EXECUTING MOVE: {disk_to_move_body_name} from peg {source_peg} to peg {target_peg} ===")
        print(f"   Source level: {source_level}, Target level: {target_level}")
        print(f"   ⚠️  NOTE: Using PLACEHOLDER movements with very slow, safe joint motions")

        # --- Execute Physical Movement Sequence ---
        # Move to a safe height above the source disk
        print(f"🔄 Step 1: Moving to approach position above peg {source_peg}...")
        self.move_to_pose(self.model.site(approach_site_src).pos, duration=8.0, viewer=viewer)
        print(f"✅ Reached approach position above peg {source_peg}")
        
        # Descend to grasp the disk (target the disk's moving site)
        # We get the site's position dynamically as the disk might have shifted
        grasp_pos = self.data.site(grasp_site).xpos
        print(f"🔄 Step 2: Descending to grasp {disk_to_move_body_name}...")
        self.move_to_pose(grasp_pos, duration=8.0, viewer=viewer)
        print(f"✅ Positioned above {disk_to_move_body_name}")
        
        # Grasp
        print(f"🔄 Step 3: Closing gripper to grasp {disk_to_move_body_name}...")
        self.set_gripper('closed', viewer=viewer)
        print(f"✅ Gripper closed - {disk_to_move_body_name} grasped")
        
        # Ascend back to the approach height
        print(f"🔄 Step 4: Lifting {disk_to_move_body_name} to safe height above peg {source_peg}...")
        self.move_to_pose(self.model.site(approach_site_src).pos, duration=6.0, viewer=viewer)
        print(f"✅ {disk_to_move_body_name} lifted to safe height")
        
        # Move to the approach height of the target peg
        print(f"🔄 Step 5: Moving {disk_to_move_body_name} to approach position above peg {target_peg}...")
        self.move_to_pose(self.model.site(approach_site_tgt).pos, duration=10.0, viewer=viewer)
        print(f"✅ Positioned above peg {target_peg}")
        
        # Descend to the correct level on the target peg
        print(f"🔄 Step 6: Descending to place {disk_to_move_body_name} at level {target_level} on peg {target_peg}...")
        self.move_to_pose(self.model.site(place_site).pos, duration=8.0, viewer=viewer)
        print(f"✅ Positioned at target placement location")
        
        # Release
        print(f"🔄 Step 7: Opening gripper to release {disk_to_move_body_name}...")
        self.set_gripper('open', viewer=viewer)
        print(f"✅ Gripper opened - {disk_to_move_body_name} released")
        
        # Ascend back to the approach height
        print(f"🔄 Step 8: Retracting to safe height above peg {target_peg}...")
        self.move_to_pose(self.model.site(approach_site_tgt).pos, duration=6.0, viewer=viewer)
        print(f"✅ Retracted to safe height")

        # --- Update Internal State ---
        moved_disk = self.peg_state[source_peg].pop()
        self.peg_state[target_peg].append(moved_disk)
        print(f"🎯 === MOVE COMPLETE: {disk_to_move_body_name} successfully moved from {source_peg} to {target_peg} ===")
        print(f"   Updated puzzle state: {self.peg_state}\n")